### ISSUE TITLE
bug: ant register edit / ant register get not working

### ISSUE THREAD

**Issue by markwylde** [maidsafe/autonomi#2751]
I'm trying to use registers to maintain a mutable reference to my game files, but I'm encountering some unexpected behavior with register updates.

I've raised this on the forums too:
[https://forum.autonomi.community/t/understanding-registers/41208/1](https://forum.autonomi.community/t/understanding-registers/41208/1)

#### What I'm trying to do

Create a register that can point to different versions of my game file, allowing me to update which version players should download.

#### Steps to reproduce

1. Create a register:

```bash
ant register create autonomi-blocks-game testing
```

2. Verify initial value:

```bash
ant register get --name autonomi-blocks-game
# Shows value: [testing]
```

3. Update the register:

```bash
ant register edit --name autonomi-blocks-game "edit-test"
# Shows success message
```

4. Read the register again:

```bash
ant register get --name autonomi-blocks-game
# Still shows original value: [testing]  
```

#### Expected behavior

After updating the register, reading it should show the new value ("edit-test").

#### Actual behavior

The register appears to retain its original value ("testing") even after a seemingly successful update operation.

#### Additional context

The CLI reports success on the update operation and even shows a transaction cost, but the change doesn't seem to persist.

#### Questions

Is this expected? Am I missing something in how registers should be updated, or is this possibly a bug in how updates are being processed?

**Comment by markwylde** [comment]
I [implemented](https://github.com/maidsafe/autonomi/pull/2752) a `ant register history` command which allows me to see the history of a register entry.

```bash
markwylde@Marks-MacBook-Pro autonomi % ./target/release/ant register history --name markwylde3

🔗 Connected to the Network                                                                                       Getting register history with name: markwylde3
✅ Register history found at: markwylde3
History of values:
[hello]
[&��AF�5��C����^t��������53��D]
markwylde@Marks-MacBook-Pro autonomi % ./target/release/ant register get --name markwylde3

🔗 Connected to the Network                                                                                       Getting register with name: markwylde3
✅ Register found at: markwylde3
With value: [hello]
```

So I think this shows that `ant register get` only gets the first change?

**Comment by grumbach** [comment]
Hi @markwylde, thanks for your contributions! Although I did not manage to reproduce your issue on a local testnet, I did manage to reproduce it in production. After some digging I've confirmed the underlying `Pointer` was not referencing to the latest head (latest register value) which explains why an old value can show up on `get`. 

Registers keep track of their latest versions through a [`Pointer`](https://docs.autonomi.com/developers/api-reference/autonomi-client/pointer) which is a mutable data type which allows for free updates (but no history). The reason the pointer sometimes doesn't point to the latest register value is that the newest version of the pointer didn't have enough time to be replicated through the network and unfortunately some nodes still hold the old pointer. Although we ensure eventual consistency, meaning everyone will be informed eventually and will hold the newest pointer, this process can take time depending on node and network performance. 

The register I had the issue with was healed after some time and some retries: you can fetch it here to try:
`a790f11235ba6983a435ff8de9fe2406f5a80ed264bc70a9dd37b3b5a57468c57d9d85bb5b001438adc279da799aa4a4`
It indeed returns the latest value when you `get` and shows matching history (thanks for your [awesome PR](https://github.com/maidsafe/autonomi/pull/2752) btw). 

Did you retry after a while? You might encounter the corrupt head pointer error, which is okay as it is the case, but retrying should fix it, and time should make the fix visible (need time for pointer update to replicate). 

We are working on improving Pointer update speed, which hopefully will reduce the chance of having issues like the above down the line. I understand that until then, depending on network conditions, it results in a poor register experience, we will do our best to improve that over time and greatly appreciate your input! 

Closing this one for now, but feel free to re-open it if your issue persists even after retries and time (replication). If so, please include your register address so we can dig more into it (you can get the address with `ant register list`).

**Comment by markwylde** [comment]
Thanks for investigating @grumbach and for the great explanation.

It's strange, because I did `markwylde3` several days ago and it's still showing the original value.

```
> markwylde in autonomi % ./target/release/ant register history --name markwylde3
🔗 Connected to the Network                                                                                       Getting register history with name: markwylde3
✅ Register history found at: markwylde3
History of values:
[hello]
[&��AF�5��C����^t��������53��D]
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register get --name markwylde3
🔗 Connected to the Network                                                                                       Getting register with name: markwylde3
✅ Register found at: markwylde3
With value: [hello]
-------------------------------------------------------------
```

Sorry that one from a few days ago is a little unclear. I've made a new one an hour ago `markwylde5` with an initial value of `first` and an edit of `second`.

```
> markwylde in autonomi % ./target/release/ant register history --name markwylde5
Logging to directory: "/Users/markwylde/Library/Application Support/autonomi/client/logs/log_2025-02-17_08-06-48"
🔗 Connected to the Network
Getting register history with name: markwylde5
✅ Register history found at: markwylde5
History of values:
[first]
[second]
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register get --name markwylde5
Logging to directory: "/Users/markwylde/Library/Application Support/autonomi/client/logs/log_2025-02-17_08-07-55"
🔗 Connected to the Network                                                                                       Getting register with name: markwylde5
✅ Register found at: markwylde5
With value: [first]
```

It's still showing the first value.

I'll try it again tonight to see if it eventually updates.

I do think you're right as if I try and update it a `third` time, I get:

```
> markwylde in autonomi % ./target/release/ant register edit --name markwylde5 third
🔗 Connected to the Network                                                                                       Enter password to decrypt wallet:
Attempting to update register at markwylde5 with new value: third
Error:
   0: Failed to update register at address: markwylde5
   1: Corrupt register: Pointer is apparently not at head, attempting to heal the register by updating it to point to the next entry at GraphEntryAddress(25a6d3), please retry the operation

Location:
   ant-cli/src/commands/register.rs:140

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
-------------------------------------------------------------
```

How long would you expect it to take to sync? Could it be longer than a day?

**Comment by happybeing** [comment]
@grumbach I think this issue should remain open until pointers update within say <1s and the behaviour should be noted in Pointer and Register docs as it is a serious bug/litation.

Nice catch @markwylde. I haven't noticed this on local, and have not used the live network yet.

It's similar to problems we had with the old Register imp going back many months.

**Comment by markwylde** [comment]
Thanks both!

I just tried again, and it's still not synced (7 hours later)

```bash
> markwylde in autonomi % ./target/release/ant register list
Retrieving local user data...
✅ You have 3 register(s):
markwylde5: 8266f4664e49b4f0d59e952ea7be0618fa8170b8122e7ba4488cb6841c446fbdc02414a1e5bffda063cd867b136bcd78
markwylde4: a84d4ee56bef626faaab864244c04d09919aa7fff5fd1183b49b14437acd334702b86c81b8cefdcff06b1af6a81a8c4e
markwylde3: 9260f5777b4c2ad1d127930ff195babfc0ac85f00d048b43453cfe412b9c1dd66d78bb55e87ea4330aea6464990bbad1
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register get --name markwylde5
🔗 Connected to the Network                                                                                       Getting register with name: markwylde5
✅ Register found at: markwylde5
With value: [first]
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register get 8266f4664e49b4f0d59e952ea7be0618fa8170b8122e7ba4488cb6841c446fbdc02414a1e5bffda063cd867b136bcd78
🔗 Connected to the Network                                                                                       Getting register at address: 8266f4664e49b4f0d59e952ea7be0618fa8170b8122e7ba4488cb6841c446fbdc02414a1e5bffda063cd867b136bcd78
✅ Register found at: 8266f4664e49b4f0d59e952ea7be0618fa8170b8122e7ba4488cb6841c446fbdc02414a1e5bffda063cd867b136bcd78
With value: [first]
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register edit --name markwylde5 third
🔗 Connected to the Network                                                                                       Enter password to decrypt wallet:
Attempting to update register at markwylde5 with new value: third
Error:
   0: Failed to update register at address: markwylde5
   1: Corrupt register: Pointer is apparently not at head, attempting to heal the register by updating it to point to the next entry at GraphEntryAddress(25a6d3), please retry the operation

Location:
   ant-cli/src/commands/register.rs:140

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
-------------------------------------------------------------
> markwylde in autonomi %
```

**Comment by happybeing** [comment]
As a follow up:

I think we can assume there will always be a delay or the possibility of a delay, and for different gets of a pointer to return different values. I saw this with the earlier register implementation and think it is just a property of not trying for true concensus. 

So I propose:
- we document that Pointer behaviour as expected
- we treat the Register (and my similar `dweb::trove::History`) pointers as "likely to be near the head" of the graph. So when getting the head, we use the pointer the candidate GraphEntry and then follow it to the end to ensure we have the head.

I think that should be good enough and will be implementing this for my `History`.

**Comment by markwylde** [comment]
I just tried again, been a day and a half, but still not synced.

```bash
> markwylde in autonomi % ./target/release/ant register edit --name markwylde5 third
🔗 Connected to the Network                                                                                       Enter password to decrypt wallet:
Attempting to update register at markwylde5 with new value: third
Error:
   0: Failed to update register at address: markwylde5
   1: Corrupt register: Pointer is apparently not at head, attempting to heal the register by updating it to point to the next entry at GraphEntryAddress(25a6d3), please retry the operation

Location:
   ant-cli/src/commands/register.rs:140

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register get --name markwylde5
🔗 Connected to the Network                                                                                       Getting register with name: markwylde5
✅ Register found at: markwylde5
With value: [first]
-------------------------------------------------------------
> markwylde in autonomi % ./target/release/ant register history --name markwylde5
🔗 Connected to the Network                                                                                       Getting register history with name: markwylde5
✅ Register history found at: markwylde5
History of values:
[first]
[second]

```

@grumbach would you please reopen this issue, if that's okay?

**Comment by grumbach** [comment]
Thanks guys! Reopened the issue as indeed a "day and a half" is not a reasonable wait time to get a Pointer updated! Will keep digging! 

I've got an attempt here to improve `Pointer` accuracy: https://github.com/maidsafe/autonomi/pull/2753 (was merged in main). It managed on my side to fix a similarly broken register after some retries (more `register edit`). Could you give it a try and tell me if it changes anything (just try on latest main)?

**Comment by markwylde** [comment]
Thanks @grumbach 

This is looking much better. `markwylde6` and `markwylde7` all went through.

## Create a register
```
> markwylde in autonomi % time ./target/release/ant register create markwylde7 first
🔗 Connected to the Network
Enter password to decrypt wallet:
Creating register with name: markwylde7
✅ Register created at address: a3299e3b74ddf215b39d1ab5b8d36dcb58d65e7a3515b61bd3e8a840e3a9fb53a69a15b0be91a283681de80346f430d2
With name: markwylde7
And initial value: [first]
Total cost: 0.00000000000000000000022410005655 AttoTokens

21.99s user 57.50s system 36% cpu 3:37.11 total
```

## Get the register value
```
> markwylde in autonomi % time ./target/release/ant register get --name markwylde7
🔗 Connected to the Network
Getting register with name: markwylde7
✅ Register found at: markwylde7
With value: [first]

12.85s user 19.88s system 170% cpu 19.142 total
```

## Update the register value
```
> markwylde in autonomi % time ./target/release/ant register edit --name markwylde7 second
🔗 Connected to the Network
Enter password to decrypt wallet:
Attempting to update register at markwylde7 with new value: second
✅ Successfully updated register
With value: [second]
Total cost: 0.00000000000000000000000055880967 AttoTokens

16.65s user 40.84s system 57% cpu 1:40.59 total
```

## Confirm the register value is updated
```
> markwylde in autonomi % time ./target/release/ant register get --name markwylde7
🔗 Connected to the Network
Getting register with name: markwylde7
✅ Register found at: markwylde7
With value: [second]

12.65s user 18.50s system 165% cpu 18.855 total
```

## Edit a third time
```
> markwylde in autonomi % time ./target/release/ant register edit --name markwylde7 third
🔗 Connected to the Network
Enter password to decrypt wallet:
Attempting to update register at markwylde7 with new value: third
✅ Successfully updated register
With value: [third]
Total cost: 0.00000000000000000000000055880967 AttoTokens

16.11s user 44.55s system 87% cpu 1:09.64 total
```

## Get history
```
> markwylde in autonomi % time ./target/release/ant register history --name markwylde7
🔗 Connected to the Network
Getting register history with name: markwylde7
✅ Register history found at: markwylde7
History of values:
[first]
[second]
[third]

17.49s user 43.19s system 57% cpu 1:45.41 total
```

## Get latest value
```
> markwylde in autonomi % time ./target/release/ant register get --name markwylde7
🔗 Connected to the Network
Getting register with name: markwylde7
✅ Register found at: markwylde7
With value: [third]

12.56s user 18.81s system 137% cpu 22.782 total
```

The timings are quite slow:

ant register get: 19.142s

ant register edit: 100.59s
ant register get: 18.855s

ant register edit: 69.64s
ant register history: 105.41s

ant register get: 22.782s

**Comment by happybeing** [comment]
> we treat the Register (and my similar dweb::trove::History) pointers as "likely to be near the head" of the graph. So when getting the head, we use the pointer the candidate GraphEntry and then follow it to the end to ensure we have the head.

@markwylde I've implemented the above for `dweb::trove::History<T>` and it works well, except that finding the head of the graph means waiting for an entry at the end to "not be found" on the network.

That takes more than 20s which is too long. So I've:
- managed to avoid this when updating (adding an entry)
- provided some control to enable apps to avoid doing this unless absolutely necessary

On the last point, it means you can for example keep track of the most recent `pointer.counter()` value and use this to avoid looking for another entry if it matches (or is less than the retrieved `pointer.counter()`)

BTW Mark, I have pushed this to github but not yet to crates.io. I want to update the README before doing that. I have also realised it would be possible to allow `History<T>` to operate on Register pointer/graphs, but don't yet plan to do this - too many other interesting things.

@grumbach any faster than ~20s ways my code could discover that a `GraphEntry` doesn't exist would be useful to know about, but I think what I have will do for now. On the other hand if your fix can guarantee pointer update in a few seconds that would avoid the need for much of this. I think that would cover a lot of use cases.

**Comment by grumbach** [comment]
@markwylde glad this helped fix the issue! Performance is still not ideal indeed! 
@happybeing, you can try using:
https://docs.rs/autonomi/latest/autonomi/struct.Client.html#method.graph_entry_check_existance
Which should be faster than a regular `graph_entry_get`

**Comment by happybeing** [comment]
FYI `graph_entry_check_existance()` knocks 0-3s off the 20s on a  local testnet but on the live network it takes *minutes* when the entry does not exist.

**Comment by happybeing** [comment]
Just confirming I'm still seeing this. @willief created a website a few days ago and I was testing an app using it. The process he used creates and then updates the pointer when publishing the first version of his website (ie two graph entries). I can see that he updated it once after that, so the graph has three entries in total (the first is not used for a website but reserved for a 'type').

You can see from the following output (using `dweb inspect-history`) that the pointer doesn't even have the first update as its counter is still at 0 and is pointing to the root.

N.B. In the output below, `P>` shows where the pointer is pointing to in the graph.

```
dweb inspect-history -f -e '0:' b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96`

Dweb Autonomi client initialising...
🔗 Connected to the Network                                                                                                       -> public network evm-custom
DEBUG pointer counter: 0, head address: b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96
DEBUG History::update_from_graph_internal()
DEBUG stepping forwards: iter_index 0
DEBUG GraphEntry exists
DEBUG stepping forwards: iter_index 1
DEBUG GraphEntry exists
DEBUG stepping forwards: iter_index 2
DEBUG GraphEntry does not exist
history address  : b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96
  type           : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
  size           : 3
  pointer address: b0d75e520ad552d8a56fa43be47704384345eb17be853cf7722276c0728340bb18185388b5007840378ec5e653c09a9d
  graph root     : b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96
  graph head     : ab091bcc0626fb3ac194edb197b9ee533efdba65842f3a97e39450c017656df0763368bc369e2fbfde8049edca28d9dd
  entries 0 to  2:
P>  entry    0:
	address   : b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96
	  owner      : b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96
	  parents    : 
	  descendents: [860f74d61151628b96e7f0daacac639a24c48d9a0a86b6c1acc49aaaffb18a7fb868b810108d09383672a355b15e6039] 
	  content    : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
	  signature  : 81b8e73d43d4486ab4327187548be6f65119533cd69cbb162186ea44281b9264646ced6efb00b0f8f1839b96bc3f5db10d857cb97ca6dddbcdf4308b9aef4d8c3e914ed872fc8cca4ea7cfc3351b8369ba41acd80f956f5502be9c5d5425f075
DEBUG GraphEntry exists
	entry    1:
	address   : 860f74d61151628b96e7f0daacac639a24c48d9a0a86b6c1acc49aaaffb18a7fb868b810108d09383672a355b15e6039
	  owner      : 860f74d61151628b96e7f0daacac639a24c48d9a0a86b6c1acc49aaaffb18a7fb868b810108d09383672a355b15e6039
	  parents    : [b4d001a4b826cf9cfca6101f35da73d21c2464ab8abf4d054ea99ecd9a57858f9c74854ae1acf856d244aba5d4a0ed96] 
	  descendents: [ab091bcc0626fb3ac194edb197b9ee533efdba65842f3a97e39450c017656df0763368bc369e2fbfde8049edca28d9dd] 
	  content    : eb02924f63b257a12f4bb856563ba821d483fbf18cb6d962e89a3e0a46020a92
	  signature  : b310651899f4ab15ee83c583ba018a5d62fea492fcfea43ee20e9fe42ba28b9e73a988b0210a15e5174cbaae12c1cd08018edfd690cde9a5403564cc91e7abdb445b2ef9ce790718f874c163438244e9ed1f547b3b01ae55f0afa0e27c1914c4
DEBUG GraphEntry exists
	entry    2:
	address   : ab091bcc0626fb3ac194edb197b9ee533efdba65842f3a97e39450c017656df0763368bc369e2fbfde8049edca28d9dd
	  owner      : ab091bcc0626fb3ac194edb197b9ee533efdba65842f3a97e39450c017656df0763368bc369e2fbfde8049edca28d9dd
	  parents    : [860f74d61151628b96e7f0daacac639a24c48d9a0a86b6c1acc49aaaffb18a7fb868b810108d09383672a355b15e6039] 
	  descendents: [ae2bcb10a121158d115f9782adee7cd594dff6da6ebcd9a7bc39397c7e78aa3a81412e158c3c411ec6948e41ef9f7709] 
	  content    : 9021db42d84e062aa290eb9792b4c933b22b0f34bf4ba3a8f754ac7928d33170
	  signature  : 9421d90f2a8bb6eb128cc3ecbcbfbdfe2ccfe2365a443ca3ef0ba7a453af57bd8b44b66b5ba486f2be525ba569ddc2950e518acc8d0ee435b84e043a7ac677727d81eb4de84223306c414e63e9fed1b3efd269ffec575d3c93ada97cdf6fb263
```

**Comment by happybeing** [comment]
Another confirmation this is still present in the latest v0.4.4 Autonomi network. @willief created a new site a couple of days ago and has updated it a few times. The pointer should be updated to point at the most recent (highest number entry) each time but you see from the `P>` below that it is stuck pointing at entry zero. I have also checked and the counter remains at 0 too, while the same code is working on a local testnet for me.

The following is generated using the `dweb inspect-history` command for @willief's latest website:
```
$ dweb inspect-history -pdfe 0:  b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6
[snip]
DEBUG from_history_address() returning History with num_entries: 4
history address  : b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6
  type           : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
  size           : 4
  pointer address: a9d96ebccb2d3813370a0f6ac409b6edfe17eb31cd996f4b7a56b746af92a5ab218701815721829f18b8f744c7fe39a0
  graph root     : b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6
  graph head     : 90c9bc332113d3e5e6617fd9ec324340ffa1faac1abd1641cd98397c91610486ba84039c8d7d469cbca44ad38d580f5e
  entries 0 to  3:
DEBUG INSPECT history.pointer_counter(): 0
P>  entry    0:
    address   : b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6
      owner      : b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6
      parents    : 
      descendents: [829f340caadebccaf0404a15a4746f82aaa8f03ed5cbf9cd59afe69a945d9cd0498e80809fd22a2b025bfb20ed700979] 
      content    : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
      signature  : aa15258162bb68628cfa548fdae37db5f612bfa61178844c5c7d9dbc7289edf57507facfa30a2e6ca9bc73bda0dcd4b5003f45d07ea0ac346c0a8423343ba792c7a116fea5eeccd00ad181bfb9ab47f57a3ba7a32b543eef00c70f7145cbe53a
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 0
    entry    1:
    address   : 829f340caadebccaf0404a15a4746f82aaa8f03ed5cbf9cd59afe69a945d9cd0498e80809fd22a2b025bfb20ed700979
      owner      : 829f340caadebccaf0404a15a4746f82aaa8f03ed5cbf9cd59afe69a945d9cd0498e80809fd22a2b025bfb20ed700979
      parents    : [b719b34d662b670cc2f7b2ee89a1d33293ffb36d1dddadc807527a8913cb52ea7eb9b9d22293454d2e612ccfab4400a6] 
      descendents: [a0444c834199a765b57c844d28a07841c4732afdcad6d6064357bd42592b33e5b0036d8868c04231c3a65e532cf137e3] 
      content    : bdeb1426ab6462cefd24fa8655de31ee736ceb9a432e04eb8a965617a31c68d8
      signature  : 8282c5210120274f998615d5e0bbc91f1d91cc92d9d6c77d1f399969fcf7b2b9df8f3174fb389681d5c4bb7f2d8aeedd1769f95b73d88b70265192b24a3d7a70202a24322eb0f947bc2392eee3bffee7efe615385b8e2ff2c6ba156043c43f10
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 0
    entry    2:
    address   : a0444c834199a765b57c844d28a07841c4732afdcad6d6064357bd42592b33e5b0036d8868c04231c3a65e532cf137e3
      owner      : a0444c834199a765b57c844d28a07841c4732afdcad6d6064357bd42592b33e5b0036d8868c04231c3a65e532cf137e3
      parents    : [829f340caadebccaf0404a15a4746f82aaa8f03ed5cbf9cd59afe69a945d9cd0498e80809fd22a2b025bfb20ed700979] 
      descendents: [90c9bc332113d3e5e6617fd9ec324340ffa1faac1abd1641cd98397c91610486ba84039c8d7d469cbca44ad38d580f5e] 
      content    : 40c159a125060e838e4fd087df2cfe34c7f711deb4f1659a61201bd8624cc830
      signature  : 807352e1848302267cae4571673f632845ced761733cde1e5c03f02c7078064a55628e2a70c9eefd75920b915e4493370c2db56d80fce24d25defd3ead66e447299bf47b841e5bf9b066129bda639e7f712e900eff5fab77a378a736b13f251e
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 0
    entry    3:
    address   : 90c9bc332113d3e5e6617fd9ec324340ffa1faac1abd1641cd98397c91610486ba84039c8d7d469cbca44ad38d580f5e
      owner      : 90c9bc332113d3e5e6617fd9ec324340ffa1faac1abd1641cd98397c91610486ba84039c8d7d469cbca44ad38d580f5e
      parents    : [a0444c834199a765b57c844d28a07841c4732afdcad6d6064357bd42592b33e5b0036d8868c04231c3a65e532cf137e3] 
      descendents: [8514ca19bb058e73a836166bd1d6944eb135be453852015e2453842c00b5a80689bfcc3f7da6e3d7e588a1d762a35610] 
      content    : 40c159a125060e838e4fd087df2cfe34c7f711deb4f1659a61201bd8624cc830
      signature  : 99e94371433f6bbd5253c2c50413b02ce181692b60f44a214eef6e61cc2fb45f10dbb8c25df667add67769aae507ef350bd52bd73f90b5e528cf0245bdd652debd365b0671cf996f561acd96c15caf00857a6058c70557f93d52196fcac1dae3
```

The following is the same command for one of my test websites run on a *local testnet*. You will see that the `P>` points to the most recent entry (entry 5), not to entry 0:
```
     Running `target/debug/dweb --local inspect-history -pdfe '0:' b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833`

Dweb Autonomi client initialising...
DEBUG loaded wallet: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
DEBUG     tokens: 2499999999999999999997360
DEBUG     gas   : 9999996514930282931378
-> local network: evm-custom
DEBUG History::from_history_address(b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833)
>>TRYING pointer_get() 1 times...
>>TRY 1 of 1
DEBUG pointer counter: 5, head address: 9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9
>>OK
DEBUG INSPECT pointer_counter: 5
DEBUG INSPECT pointer_target : 9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9
DEBUG History::update_from_graph_internal()
DEBUG stepping forwards: iter_index 5
DEBUG GraphEntry does not exist
DEBUG from_history_address() returning History with num_entries: 6
history address  : b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833
  type           : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
  size           : 6
  pointer address: b6bc89501dc7f8e41d76a613991a639b093753028613f728b4fbe3213c481c20029646b6cd733e0fad4a1f76b0602e04
  graph root     : b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833
  graph head     : 9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9
  entries 0 to  5:
DEBUG INSPECT history.pointer_counter(): 5
    entry    0:
    address   : b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833
      owner      : b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833
      parents    : 
      descendents: [8d7224ac7a696a1dca1a3fd7079adbcb545c8ddaa38ddc4ef1af5e103cf089df874c202b03e4a562eeed413190b4fcdb] 
      content    : ee383f084cffaab845617b1c43ffaee8b5c17e8fbbb3ad3d379c96b5b844f24e
      signature  : b7c12d94ed33eed497878061374d4d157ed1fbced6d905a829a7b7b5e28a5919e1a56c42a46d65fe7d4b3d717f2f13fe0c9a941b0746d4702ff3399e56aef8f00c2838a458f1ed61ba0bbecf7a493f61bc1c5c9e45f2ae5b2b69981c99491523
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 5
    entry    1:
    address   : 8d7224ac7a696a1dca1a3fd7079adbcb545c8ddaa38ddc4ef1af5e103cf089df874c202b03e4a562eeed413190b4fcdb
      owner      : 8d7224ac7a696a1dca1a3fd7079adbcb545c8ddaa38ddc4ef1af5e103cf089df874c202b03e4a562eeed413190b4fcdb
      parents    : [b26ba8d98417a52b5399f99234e1493ee9d20cfd5f5a11bbf2a7d04a752bf4b89d86c123b0478fddd27a718cd29e5833] 
      descendents: [80d31c07c4204bf45877332c088586a69b98f7f133b3b965200623cc04d3e29c6c4ce46f28e415edaa921f21c358b6ca] 
      content    : 450065eab8f44c439c2bbac122caf9ca71a96a815554357ffd7e698d3597796f
      signature  : b31669faeec81443a96f3adad8a7b461bfa450a45e86168cf88f5ff115920807825e05b3ab6ed61cf01c1c5b6fc57f21147fe432f97738b0b29c56f5b113e7bf5473acd97dc6926bb1d3890cf969a34f955c49bc7ac487ead9a32c24f9861585
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 5
    entry    2:
    address   : 80d31c07c4204bf45877332c088586a69b98f7f133b3b965200623cc04d3e29c6c4ce46f28e415edaa921f21c358b6ca
      owner      : 80d31c07c4204bf45877332c088586a69b98f7f133b3b965200623cc04d3e29c6c4ce46f28e415edaa921f21c358b6ca
      parents    : [8d7224ac7a696a1dca1a3fd7079adbcb545c8ddaa38ddc4ef1af5e103cf089df874c202b03e4a562eeed413190b4fcdb] 
      descendents: [8e1c55a617d9d3e816290bd7c470fc1da5f862c3993e52f8e1cc298e9b71c38a32a7373b7e5dd3a34033e2d0a46711d6] 
      content    : 4836df01b92e1afaf76534e0b5aaca3c8cde236489f040b3b19aa6f74b79f25b
      signature  : 8a961e1d124fed548267239150bb16c3bcdcc3d08d63e419f1d54e0f7cb49f058cc95d061ab52970243cd48b4c7da7f4112cc48dcb9fdeb12ab8bd31920ecaa1bda404692720df2157189a8e42583e494624b36da67205dc553166b4ebe50c20
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 5
    entry    3:
    address   : 8e1c55a617d9d3e816290bd7c470fc1da5f862c3993e52f8e1cc298e9b71c38a32a7373b7e5dd3a34033e2d0a46711d6
      owner      : 8e1c55a617d9d3e816290bd7c470fc1da5f862c3993e52f8e1cc298e9b71c38a32a7373b7e5dd3a34033e2d0a46711d6
      parents    : [80d31c07c4204bf45877332c088586a69b98f7f133b3b965200623cc04d3e29c6c4ce46f28e415edaa921f21c358b6ca] 
      descendents: [8200671e0eabe8bba914b4f71a4ae405d3970872a9d35d49dad66867e34b463714983263e319b128434a368c7395e93d] 
      content    : 0819b3ccfa2d18c44a0725781cd46fa0b42885384c46d41dbb1e88fb25222e68
      signature  : 8b9db5a648cf8e80aa9b6551fb71ad30745a91fb89c9fd76baba16c8d57ab84fce0dd709a79b2b8d9b3362ef07f97bf40226ab7c355ede389e137aea03767e105a5a2a0fb32c9db8d1abf2ab1ff207785e010fc94b16c2cdc408178a5dad553a
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 5
    entry    4:
    address   : 8200671e0eabe8bba914b4f71a4ae405d3970872a9d35d49dad66867e34b463714983263e319b128434a368c7395e93d
      owner      : 8200671e0eabe8bba914b4f71a4ae405d3970872a9d35d49dad66867e34b463714983263e319b128434a368c7395e93d
      parents    : [8e1c55a617d9d3e816290bd7c470fc1da5f862c3993e52f8e1cc298e9b71c38a32a7373b7e5dd3a34033e2d0a46711d6] 
      descendents: [9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9] 
      content    : d1b8e74d57d82061b211d2a4a4ea3f97643b879cc8839c0b4c0563f94b4f9b8a
      signature  : b2a3212557fca3c01b753415bd2abaee36f0e08a17e783325952a077b009036657948643b0b7e763c5d6fa7da5e1568611399a19ee3e3a2d747cf6c0dd60d24699cac9ec8dc2655fa93a1e3666714879c8de784f949a5425ab17e94e3227b71d
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 5
P>  entry    5:
    address   : 9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9
      owner      : 9186f537a67277606208a62bec3f37c5b2e627d75619075cca3e794e308ce6c7e325ad3ffe24a21f45ac01eee20e8cb9
      parents    : [8200671e0eabe8bba914b4f71a4ae405d3970872a9d35d49dad66867e34b463714983263e319b128434a368c7395e93d] 
      descendents: [97fa8b05cb8ae181a892c87c5ddccd689628f9ae04f6cd47922baeab08f27b2fd37304dfe5db21f1518f1e56283036d9] 
      content    : 79eaf92abbdb4b911bec1b8e3b864499a7126e1768eeaf3c6d44c6c6da87a4d9
      signature  : 8a0d1d4c91c53b87c36c799b4ff359d6ee0594fc852b84b8f1867e87bff1513ffddaf59cc132187ca612aebf9d44b40917445369284d4499828982bf021db6228273de8d01d39ebc31214427bb64308e9266ce4edadd1be2545d71cf9a44f39d
```

**Comment by happybeing** [comment]
<strike>SOLVED: for me ... my issue has been that for some time Pointers have not been updating at all but I now have this working.</strike> I don't know how much if any delay remains at this point.

EDIT: I thought this was working but it's reverted: a pointer that had been stuck at 0 since creation despite using pointer_put() to update it - appeared fixed by using repeated pointer_update() until it was at the correct count/target. (I made a heal-history subcommand for dweb to do this).  However a day or two later I'm repeatedly getting the stuck at 0 pointer back. 🤦‍♂ 

CAUSE: After creation using pointer_put() I was also using pointer_put() for updates instead of pointer_update(). I don't know why, but pointer_put() only works on first use so I've switched to only use pointer_create() and pointer_update().

BUG: It may still be a bug that you cannot use pointer_put() to update a Pointer <edit>and that pointer_put() returns success</edit>. I suggest either it is treated as a bug, or the function doc/comment is amended to avoid use for updating an existing Pointer.

**Comment by happybeing** [comment]
@Nic-dorman as you mentioned that this will be looked into after Client Light Networking, please can you re-open this or point it to an issue to ensure problems with Pointers reported here will be addressed. 

Please can you also tell me what "linear closed this" means and why it would be treated as completed? Seems problematic and not the first time I've seen this. Thanks.

**Comment by vphongph** [comment]
Hi @happybeing!

I think linear closed it because I put the issue as "done" yesterday, I was investigating the bug and I couldn't reproduce it.
I didn't know Linear and Github was linked and behaving like that!

Yesterday I was testing the CLI ant register commands and I could create, get, edit and history.
I didn't encounter any issue.
I just ran additional tests, I had no issue as well.

I do sometimes need to wait few minutes due to inertia/latency in the network.

<img width="957" alt="Image" src="https://github.com/user-attachments/assets/77cfac9e-6ccf-4131-8be3-c03e59c96836" />
<img width="957" alt="Image" src="https://github.com/user-attachments/assets/7abae7de-67e8-4dcc-9ec9-d81f1b276bcb" />
<img width="959" alt="Image" src="https://github.com/user-attachments/assets/da94f5e0-8fa6-4620-a1ca-dc38a1f7efd9" />

____

Could explain again what is the problem you have with the pointer update?
What is your success rate? Does it fail all the time?

**Comment by happybeing** [comment]
> Yesterday I was testing the CLI ant register commands and I could create, get, edit and history.
I didn't encounter any issue.

All the reports I've made explain what's happening on mainnet and mention that everything works fine in local testnets. I'm not sure what additional info you need from me other than what is already in my replies above, and you can check the status of pointers using dweb (cargo install dweb-cli) as shown in this reply above: https://github.com/maidsafe/autonomi/issues/2751#issuecomment-2839198446

The behaviour is sporadic and precisely how good/bad does seem to have varied over time. Most recently I've noticed pointers are created but don't update at all. Then I tried to 'heal them' (`dweb heal-history`) and they appeared to have been updated correctly, but a couple of days after that I found pointers back at counter 0, so in this case they appeared to revert to an earlier value.

So if you were to just create, update and test within a short period, maybe you won't see this effect. 

There are several Histories (which are closely based on the Register code) baked into dweb which you can list using `dweb list-names` and then use the following command to inspect the History and see where the pointer is pointing:

```
dweb inspect-history -fe 0: <ADDRESS>
```

After creating a History it has two entries and the Pointer will have been created with the first, and then updated to the second. This is because I use the first as a 'type' identifier for the History.

So a History with just one version entry will have Pointer counter 1 and two GraphEntries. I should *never* see a Pointer with counter 0 after creation. But as you see below, the Pointer counter for the following History (which has two entries) is 0 instead of 1:
```
$ dweb inspect-history -fe 0: 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
Dweb Autonomi client initialising...
DEBUG loaded wallet: 0xFB8B4DC5e7117835f1D0A08dDe366f4F66ce7909
DEBUG     tokens: 1685370484307893183414
DEBUG     gas   : 88512893640477883
-> public network evm-arbitrum-one
DEBUG History::from_history_address(95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448)
>>TRYING pointer_get() 1 times...
>>TRY 1 of 1
DEBUG pointer counter: 0, head address: 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
>>OK
DEBUG INSPECT pointer_counter: 0
DEBUG INSPECT pointer_target : 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
DEBUG History::update_from_graph_internal()
DEBUG get child of GraphEntry index 0 - child...
DEBUG GraphEntry exists
DEBUG get child of GraphEntry index 1 - child...
DEBUG GraphEntry does not exist
DEBUG from_history_address() returning History with num_entries: 2
history address  : 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
  type           : 89d56e1dd78941e18b36d75d339014aa845bee4d8cce2ca9d608c0e8e432308a
  size           : 2
  pointer address: 89da0fa0a573c99c8909c3e4790e1463a2fba21e76af33d5ad76fd28ad84fcf947a7d0d0aaf6244ee207f69556f2ae62
  graph root     : 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
  graph head     : 8fe7a25ab65b564f2869979bc47579401788cd1005c5003ec1e77199cafb19c0761ff6808af8cdcda5b87d42854e4d91
  entries 0 to  1:
DEBUG INSPECT history.pointer_counter(): 0
P>  entry    0:
    address   : 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
      owner      : 95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448
      parents    : 
      descendents: [8fe7a25ab65b564f2869979bc47579401788cd1005c5003ec1e77199cafb19c0761ff6808af8cdcda5b87d42854e4d91] 
      content    : 89d56e1dd78941e18b36d75d339014aa845bee4d8cce2ca9d608c0e8e432308a
      signature  : b1faa3ab7d398719d0ac7d9d68d43c692474e97d9ae3ebcb5cc10f424b1c5070740b0967feade30888b09fe022de9a83032a7b38cb551c3ab30f405b1ec6bd5ae522a4d2a8b5b193b9119c7186dc0efcd061222e0847af2e82681f197ec807fd
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 0
    entry    1:
    address   : 8fe7a25ab65b564f2869979bc47579401788cd1005c5003ec1e77199cafb19c0761ff6808af8cdcda5b87d42854e4d91
      owner      : 8fe7a25ab65b564f2869979bc47579401788cd1005c5003ec1e77199cafb19c0761ff6808af8cdcda5b87d42854e4d91
      parents    : [95be239165b7016b7f6dada20134438e038d0456bff04ec37943e95742726854225aa03faeed4e7bbd96f5383a8f9448] 
      descendents: [9666fd49e51e8f98b815a519fe0188264dfa56034c69eec9be59295baefc47a138f8742ffe68894501b10d46e307009d] 
      content    : 1ee0257375ccac48530ce4d85f1ee6340f179bb33f6d4f31e27fd0521e4fad3c
      signature  : 844a9ed2a6e3eec7bc1352b2ed1690a8d830d6db4ae9a9cafe4a04740d6da736cb8aa23a3ea08ae0b64d056386eaa2a4036ce5bb361fdd31ab33ecabf5abccc67e62893772fd6c9183250285065ef5b0416cba26bd9308d321dfb5f67be98451
```
You can try creating a History yourself if you have a directory called 'vphongph' with a simple index.html file in it as follows:

```
dweb publish-new -n vpongph --files-root vphongph
```
The above uploads the directory and creates a History with two entries, the first a fixed value (the type) and the second entry pointing to the Archive that was uploaded, and the Pointer will have counter value 1. You can inspect that as above, using the History address.

This code uses the same APIs as Registers and was largely copied with minor refactoring, and since it all works perfectly on local testnets I assume that mainnet behaves differently over time.

Thanks for looking into this, I hope we can figure out what's happening!

**Comment by vphongph** [comment]
Hi @happybeing !

So you're saying the pointers lose their updates over time? After a couple of days?
And currently they don't update at all?

I have few requests:
- Can you help me when you say sporadic? Does this issue affect - let's say - a couple of pointers over 1000?
- Can you also provide some non working pointers currently stored on the mainnet? or alphanet?
I saw this comment https://github.com/maidsafe/autonomi/issues/2751#issuecomment-2839198446, are the addresses still alive?
- On a "bad" pointer, can you share the specific key of this pointer? So we can work with it also.

I forgot to precise but the tests I ran previously were on the mainnet from the stable/release version of Autonomi, I know local testnets and mainnet are 2 worlds.

____

Today, I ran CLI command "register get" and "register history" from the register of my previous tests. It worked on my end.

![Image](https://github.com/user-attachments/assets/827d0047-663c-4693-b28b-c029d8ae2b59)

![Image](https://github.com/user-attachments/assets/049402b8-fba2-4cbb-a6c5-2dbb4bf3f628)

____

Today I also ran CLI commands "pointer create", "pointer edit" and "pointer get" on the mainnet from the main branch of Autonomi. It worked on my end.

![Image](https://github.com/user-attachments/assets/225bb462-5cb0-4a9d-95b1-179e60c1aba1)

![Image](https://github.com/user-attachments/assets/c0cde281-4f92-4b28-b115-809701e39e52)

![Image](https://github.com/user-attachments/assets/77a5840b-5c62-4b50-8962-d67b84ffa0f1)

____

I will watch the pointer I created and check in few days if the update is lost.

The next release on Thursday will include a lot of fixes and the Client Light Networking, so you will be able to test on it!

Also you can test on @grumbach branch: https://github.com/grumbach/autonomi/tree/scratchpad_cli_integration
This one has the new CLI pointer commands!

____

So far, on my end

[Mainnet - Stable branch]
Create register ✅
Update register ✅
Get register ✅
History register ✅
Get register after 4 days ✅
History register after 4 days ✅

[Mainnet - Main branch]
Create pointer ✅
Update pointer ✅
Get pointer ✅
Get pointer after few days - In progress

**Comment by happybeing** [comment]
I'm still seeing an issue on occasions but have not tried the branch you referred to yet. I'm posting this because I was hoping I'd made a mistake about this (a change that might make it appear to be still a problem) but that the problem had in fact gone away, but this confirms there is still an issue.

The following is a History (Pointer + Graph) created by a community member has a pointer address of: 
```
a6376caed65caff7758403d3e1c2f0e4ea705934f4808bb4251dbb9a27431bc6a346ad6d6ecb410fa0a1ee147bd63f99
```

Here you will see that the Pointer did update once (from 0 to 1) when if first published his website, and one day later (I think) he did a `pointer_update()` with dweb but the pointer has remained at count 2:
```
$ dweb inspect-history -pdfe 1: b3f448c9b4820e7ce4ec620220d612fec039155b6754727de7cc1ecf46d3546b6f8bfa18671b266914af3d3acae78e82
Dweb Autonomi client initialising...
DEBUG loaded wallet: 0xFB8B4DC5e7117835f1D0A08dDe366f4F66ce7909
DEBUG     tokens: 1688994457926247711943
DEBUG     gas   : 88313422171550883
-> public network evm-arbitrum-one
DEBUG History::from_history_address(b3f448c9b4820e7ce4ec620220d612fec039155b6754727de7cc1ecf46d3546b6f8bfa18671b266914af3d3acae78e82)
>>TRYING pointer_get() 1 times...
>>TRY 1 of 1
DEBUG pointer counter: 1, head address: aacf5c7cc3e456460f97236423b0e38338de62d773dec3d1a7a8bec1433e27e31e4f4969a7908e1562b1715622e1cdcc
>>OK
DEBUG INSPECT pointer_counter: 1
DEBUG INSPECT pointer_target : aacf5c7cc3e456460f97236423b0e38338de62d773dec3d1a7a8bec1433e27e31e4f4969a7908e1562b1715622e1cdcc
DEBUG History::update_from_graph_internal()
DEBUG get child of GraphEntry index 1 - child...
DEBUG GraphEntry exists
DEBUG get child of GraphEntry index 2 - child...
DEBUG GraphEntry does not exist
DEBUG from_history_address() returning History with num_entries: 3
history address  : b3f448c9b4820e7ce4ec620220d612fec039155b6754727de7cc1ecf46d3546b6f8bfa18671b266914af3d3acae78e82
  type           : 89d56e1dd78941e18b36d75d339014aa845bee4d8cce2ca9d608c0e8e432308a
  size           : 3
  pointer address: a6376caed65caff7758403d3e1c2f0e4ea705934f4808bb4251dbb9a27431bc6a346ad6d6ecb410fa0a1ee147bd63f99
  graph root     : b3f448c9b4820e7ce4ec620220d612fec039155b6754727de7cc1ecf46d3546b6f8bfa18671b266914af3d3acae78e82
  graph head     : 88945cea3279091ac94d7eecbf316543110ff024824639a09be83e95cbe24168e0915dfe282e872291cd935776bbf8f2
  entries 1 to  2:
DEBUG stepping forwards: index 1 > 0 iter_index
DEBUG INSPECT history.pointer_counter(): 1
P>  entry    1:
    address   : aacf5c7cc3e456460f97236423b0e38338de62d773dec3d1a7a8bec1433e27e31e4f4969a7908e1562b1715622e1cdcc
      owner      : aacf5c7cc3e456460f97236423b0e38338de62d773dec3d1a7a8bec1433e27e31e4f4969a7908e1562b1715622e1cdcc
      parents    : [b3f448c9b4820e7ce4ec620220d612fec039155b6754727de7cc1ecf46d3546b6f8bfa18671b266914af3d3acae78e82] 
      descendents: [88945cea3279091ac94d7eecbf316543110ff024824639a09be83e95cbe24168e0915dfe282e872291cd935776bbf8f2] 
      content    : 8728b75d9363d6e96cf84b895dce49b75da706e02641559e9f0469be071263b2
      signature  : b657a1f255a3868f063e6ee8e271fdd6a991e447791a4555355c29165162a8816a4179a06692792b05464bbfb206a0400df21b19d4a9aaac83d4a30942379a27192515f83bb57e6a10bca2b557fa20d831134e84d6756bc5650668e9120d7597
DEBUG GraphEntry exists
DEBUG INSPECT history.pointer_counter(): 1
    entry    2:
    address   : 88945cea3279091ac94d7eecbf316543110ff024824639a09be83e95cbe24168e0915dfe282e872291cd935776bbf8f2
      owner      : 88945cea3279091ac94d7eecbf316543110ff024824639a09be83e95cbe24168e0915dfe282e872291cd935776bbf8f2
      parents    : [aacf5c7cc3e456460f97236423b0e38338de62d773dec3d1a7a8bec1433e27e31e4f4969a7908e1562b1715622e1cdcc] 
      descendents: [8e180744c6b983ab5027325d1ae68efa1454ad2bf98a61db6cbb6f174b0b479edc6482c6f1cd474d6ef7a3b6cc114463] 
      content    : 22f46450f166eec9a89d40aa4c6def899f87c77c60501fb1bc5b339bbc6a094b
      signature  : a0f1d13fcf9f66947aef95d5752d1e2ed8581e7cd7b96b7593973a138178a3521f0c5f2a8734138daf0cac7cc337d2d408158912e69254ea403e9b22785227ee9cd1d826d1e946736e613ed0cd75a9a5cf3db6659c852894b5b887d35ecbf341

```

We can see how this goes once Grumbach update is in place. 🙏

**Comment by Nischal1425** [comment]
@happybeing @markwylde @grumbach I have did some fixes #2751 by querying multiple peers for pointer records and picking the highest counter. 
I have also added documentation warning about pointer_put() vs pointer_update() based on discussion in the issue.
This is my proposed idea or fix you could say: #3501
